#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)

    cmd = ('git', 'config', 'remote.origin.url')
    remote = subprocess.check_output(cmd, encoding='UTF-8').strip()
    remote = remote.removeprefix('git@github.com:').removesuffix('.git')

    print(f'https://github.com/{remote}')


if __name__ == '__main__':
    raise SystemExit(main())
