#!/usr/bin/env python3.6
import argparse
import subprocess


SSH = 'git@github.com:'
DOT_GIT = '.git'


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)

    cmd = ('git', 'config', 'remote.origin.url')
    remote = subprocess.check_output(cmd, encoding='UTF-8').strip()
    if remote.startswith(SSH):
        remote = remote[len(SSH):]
    if remote.endswith(DOT_GIT):
        remote = remote[:-1 * len(DOT_GIT)]

    cmd = ('git', 'rev-parse', '--abbrev-ref', 'HEAD')
    branch_name = subprocess.check_output(cmd, encoding='UTF-8').strip()
    print(f'https://github.com/{remote}/compare/{branch_name}?expand=1')


if __name__ == '__main__':
    exit(main())
