#!/usr/bin/env python3.6
import builtins
import keyword

KWD = '|'.join(sorted(keyword.kwlist))
BLT = '|'.join(sorted(x for x in dir(builtins) if x[0].islower()))
KWDS = fr'color brightcyan "\<({KWD})\>"\n'
BLTS = fr'color brightyellow "\<({BLT})\>"\n'


def main():
    with open('nanorc/python.nanorc') as f:
        lines = list(f)

    lines[lines.index('# keywords (generated)\n') + 1] = KWDS
    lines[lines.index('# builtins (generated)\n') + 1] = BLTS
    with open('nanorc/python.nanorc', 'w') as f:
        f.write(''.join(lines))


if __name__ == '__main__':
    exit(main())
