#!/usr/bin/env bash
set -euo pipefail
gsettings list-schemas | sort |
    xargs --replace bash -c ' \
        gsettings list-keys {} | sort | \
        xargs --replace=__ --verbose gsettings get {} __ 2>&1 \
    '
